force_send:
  description: 小爱音箱直接播放.{"message":"hello"}
  fields:
    message:
      description: TTS播放的文本内容.
      example: '你好，我不是小爱。'
    iid:
      description: 操作协议的位置 aid或pid，如：5.1
      example: '5.1'
add2msgqueue:
  description: 小爱音箱队列播放.{"message":"hello","wait_time":"3"}
  fields:
    message:
      description: TTS播放的文本内容.
      example: '你好，我不是小爱。'
    wait_time:
      description: 指定该语句播报完毕之后的等待时间,单位为秒(可选参数，默认为0).
      example: '0'
    iid:
      description: 操作协议的位置 aid或pid，如：5.1
      example: '5.1'
set_vol:
  description: 小爱音箱音量调节0-100.{"vol":50}
  fields:
    vol:
      description: 指定音量.
      example: '50'
    iid:
      description: 操作协议的位置 pid，如：2.1
      example: '2.1'
execution:
  description: 小爱音箱执行指令.
  fields:
    operation:
      description: 启动离家模式。.
      example: '启动离家模式'
    silent:
      description: 是否静默执行,(可选参数，默认为false).
      example: 'false'
    iid:
      description: 操作协议的位置 aid，如：5.5
      example: '5.5'
